FROM ubuntu:bionic

# Install dependencies
RUN apt-get update \
        && TZ="Europe/Germany" DEBIAN_FRONTENTD="noninteractive" apt-get install -y --no-install-recommends \
                tzdata

RUN apt-get update \
        && DEBIAN_FRONTENTD="noninteractive" apt-get install -y --no-install-recommends \
		tmux \
		nano \
		git \
		apt-transport-https \
		ca-certificates \
		gnupg \
		software-properties-common \
		wget

RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null \
	| gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null

RUN apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'

RUN apt-get update \
        && DEBIAN_FRONTENTD="noninteractive" apt-get install -y --no-install-recommends \
	kitware-archive-keyring

RUN rm /etc/apt/trusted.gpg.d/kitware.gpg

RUN apt-get update \
        && DEBIAN_FRONTENTD="noninteractive" apt-get install -y --no-install-recommends \
	cmake

RUN apt-get update \
        && DEBIAN_FRONTENTD="noninteractive" apt-get install -y --no-install-recommends \
  build-essential \
  python3 \
  python \
  curl \
  libcurl4 \
  unzip \
  zip \
  tar \
  gperf \
  libx11-dev \
  libxi-dev \
  libxext-dev \
  libgl1-mesa-dev \
  libglu1-mesa-dev \
  pkg-config \
  autoconf \
  autopoint \
  libtool \
  libxcb-xinerama0-dev \
  mesa-common-dev \
  libxrandr-dev \
  libxxf86vm-dev \
  libbluetooth-dev \
  libx11-xcb-dev \
  libavahi-compat-libdnssd-dev libcap2-dev \
  '^libxcb.*-dev' # this was under build-dep, also libxkbcommon-x11-de too
  
RUN cp /etc/apt/sources.list /etc/apt/sources.list~ \
	&& sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list \
	&& apt-get update
RUN apt-get update && DEBIAN_FRONTENTD="noninteractive" apt-get build-dep -y --no-install-recommends \
    qt5-default libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev  \
	grpc \
    poco \
    libvorbis \
    libogg \
    libsndfile \
    zlib \
    zeroc-ice

WORKDIR /app
RUN git clone https://github.com/ep-u-nw/mumble -b ssl-improvments-upstream
RUN sed -i 's/QSslError::SslError::SslError::OcspMalformedResponse/QSslError::SslError::OcspMalformedResponse/g' /app/mumble/src/murmur/Meta.cpp
RUN sed -i 's/CaCertificate(qlMcts)/CaCertificates(qlMcts)/g' /app/mumble/src/murmur/Server.cpp
RUN sed -i 's/QString::SplitBehavior/Qt/g' /app/mumble/src/murmur/Server.cpp
WORKDIR /app/mumble
RUN git submodule update --init
# Use old dependencies from 2021
RUN sed -i 's|git clone https://github.com/Microsoft/vcpkg.git $VCPKGDIR|git clone https://github.com/Microsoft/vcpkg.git $VCPKGDIR --branch 2021.12.01|' ./scripts/vcpkg/get_mumble_dependencies.sh
RUN sed -i 's|REF 3.7|REF a9d68a8d1d884b839f871c46b4ea94b3fc6d6527|' ./helpers/vcpkg/ports/zeroc-ice/portfile.cmake
RUN sed -i 's|SHA512 9f44de4e063d7a7b6a2b4adbae999fe3a6daafb8a7e945b616f89a453db81c41d1fec927f3149862649e5a92623c50f0ef2e0e58042c6070059b78dcf5ad9255|SHA512 c3d6ccf579b5e726e1f08ee8e8cbd7a0f175326b9538a9420f7c0ed1ee075d658ba9b72eee3b19f1c8da33b8c39681b9d0ee63fdbeccd03e6a95c18a73c4fcaf|' ./helpers/vcpkg/ports/zeroc-ice/portfile.cmake
RUN ./scripts/vcpkg/get_mumble_dependencies.sh
WORKDIR /app/mumble/build
RUN cmake "-DVCPKG_TARGET_TRIPLET=x64-linux" "-Dstatic=ON" "-DCMAKE_TOOLCHAIN_FILE=/root/vcpkg/scripts/buildsystems/vcpkg.cmake" "-Dice=OFF" "-DCMAKE_BUILD_TYPE=Release" cmake "-Dclient=OFF" "-Dgrpc=ON" ..
RUN make -j12
