FROM ubuntu:bionic
RUN apt-get update \
        && DEBIAN_FRONTENTD="noninteractive" apt-get install -y --no-install-recommends \ 
		software-properties-common
RUN add-apt-repository ppa:mumble/release
RUN apt-get update \
        && DEBIAN_FRONTENTD="noninteractive" apt-get install -y --no-install-recommends \
		mumble-server
WORKDIR /app
COPY mumble-server.ini mumble-server.ini
EXPOSE 64738/tcp
EXPOSE 64738/udp
RUN useradd -p $(openssl passwd -1 mumble-server) mumble-server
RUN chown -R mumble-server:mumble-server /app
USER mumble-server
ENV SUPW=YOUR_PASSWORD
CMD touch mumble-server.sqlite && (mumble-server -fg -ini /app/mumble-server.ini -supw $SUPW; exit 0) && mumble-server -fg -ini /app/mumble-server.ini