# Build the appropriate dockerfile in the builder folder first and tag it
FROM mumble_builder_static AS builder

FROM ubuntu:bionic
RUN apt-get update \
	&& DEBIAN_FRONTENTD="noninteractive" apt-get install -y --no-install-recommends \
		openssl \
		libcap2 \
		libavahi-compat-libdnssd-dev \
		libodbc1 \
		libsybdb5
WORKDIR /app
COPY --from=builder /app/mumble/build/mumble-server ./mumble-server
EXPOSE 64738/tcp
EXPOSE 50051/tcp
EXPOSE 64738/udp
RUN useradd -p $(openssl passwd -1 mumble-server) mumble-server
RUN chown -R mumble-server:mumble-server /app
USER mumble-server
ENV SUPW=YOUR_PASSWORD
ENTRYPOINT touch mumble-server.sqlite && (./mumble-server -fg -ini /app/mumble-server.ini -supw $SUPW; exit 0) && ./mumble-server -fg -ini /app/mumble-server.ini