# Build the dockerfile in the builder folder first and tag it mumble_builder
FROM mumble_builder AS builder

FROM ubuntu:bionic
RUN apt-get update \
        && DEBIAN_FRONTENTD="noninteractive" apt-get install -y --no-install-recommends \
		libqt5sql5 \
		libcap2 \
		libavahi-compat-libdnssd-dev \
		libqt5dbus5 \
		libprotobuf10 \
		libqt5network5 \
		libqt5xml5 \
		libqt5sql5-sqlite \
		openssl \
		libgrpc++
WORKDIR /app
COPY --from=builder /app/mumble/build/mumble-server ./mumble-server
EXPOSE 64738/tcp
EXPOSE 64738/udp
RUN useradd -p $(openssl passwd -1 mumble-server) mumble-server
RUN chown -R mumble-server:mumble-server /app
USER mumble-server
ENV SUPW=YOUR_PASSWORD
ENTRYPOINT touch mumble-server.sqlite && (./mumble-server -fg -ini /app/mumble-server.ini -supw $SUPW; exit 0) && ./mumble-server -fg -ini /app/mumble-server.ini