# Build Dockerfile_selfebuild and tag it mumble_selfbuild
FROM mumble_selfbuild_static

USER root
RUN apt-get update \
        && DEBIAN_FRONTENTD="noninteractive" apt-get install -y --no-install-recommends \
		openjdk-8-jre-headless
USER mumble-server